# Generated by Django 3.0.14 on 2022-02-21 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_check_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msg',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
